ckgproject/ckgproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path("", include("collegekhajagharapp.urls")),
    path("jsi18n/", JavaScriptCatalog.as_view, name="js-catalog"),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



ckgproject/collegekhajagharapp/urls.py
from django.urls import path, re_path
from .views import *
from . import views
app_name = "collegekhajaghar"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("Dashboard/", views.DashboardView, name="csdashboard"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("order/", CustomerOrderView.as_view(), name="csorder"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
    # path("products/<slug:slug>/", views.add_review, name="addreview"),

    path("add-to-cart-<int:dish_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("staff-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("staff-home/", AdminHomeView.as_view(), name="adminhome"),
    path("staff-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("staff-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("staff-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("staff-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("staff-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
]

ckgproject/collegekhajagharapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="CKG Staff")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    offer_price = models.PositiveIntegerField()
    normal_price = models.PositiveIntegerField(null=True, blank=True)
    carbohydrate = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    fats = models.DecimalField(max_digits=5, decimal_places=2)
    other_energy = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    view_count = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart Number({1}) of customer {0} ".format(self.customer, str(self.id))


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Pending", "Order Pending"),
    ("Order Received", "Order Received"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash", "Cash"),
    ("Khalti", "Khalti"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=30)
    preffered_date_time = models.DateTimeField(auto_now_add=False, auto_now=False)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    order_created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order Number({1}) of {0} ".format(self.ordered_by, str(self.id))

    @property
    def time_left_minutes(self):
        timenow = self.preffered_date_time
        now = datetime.now()
        result = timenow - now
        if result >= 0:
            return result.minutes
        else:
            return "Time out"

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(max_length=100)

    def __str__(self):
        return self.user.username

ckgproject/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block extraheading %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="about-section text-center">
      <h1 style="text-align:center">About Us</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error exercitationem ipsa ipsum labore maiores molestiae neque non officiis quod voluptatem. Beatae cupiditate dolorem error iste laboriosam repellendus rerum, sunt voluptates?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo laboriosam, minima neque nulla pariatur quia sapiente? Accusantium commodi esse, excepturi fuga nemo nisi officia, quaerat rem sint tempora totam voluptate!</p>
    </div>
</div>
{% endblock %}

ckgproject/templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

ckgproject/templates/all_products.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Dishes based upon Categories1</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3">
            <h3 class="cattitle"><a href="{% url 'collegekhajaghar:productdetail' p.slug %}">{{p.title}}</a></h3>
            <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
            <p class="mt-3">Price: Rs.{{p.offer_price}}
                {% if p.normal_price == 0 }
                    <div></div>
                {% if p.normal_price != 0 %}
                    <p style="display:none">{{p.normal_price}}</p>
                {% endif %}
            <a href="{% url 'collegekhajaghar:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

ckgproject/templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container m-0">
    <h3 class="titlecat text-center">All Dishes based upon Categories</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row m-1">
        {% for p in cat.product_set.all %}
        <div class="col-md-4">
            <div class="m-4">
                <h4><a href="{% url 'collegekhajaghar:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                {% if p.normal_price == None %}
                    <p class="mt-3">Price: Rs.{{p.offer_price}}</p> <P style="display:none">{{p.normal_price}}</P>
                {% else %}
                    <p class="mt-3">Price: Rs.{{p.offer_price}} <strike>Rs.{{p.normal_price}}</strike></p>
                {% endif %}
                <a href="{% url 'collegekhajaghar:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

ckgproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="College khajagharGhar at Itahari International College, IT College of Nepal, First college to implement timebased khajaghar +977 9815369883, khajgharghar@gmail.com" />
        <meta name="keywords" content="Nawaraj Luitel,student at Itahari International College|IIC|iic,khajgharghar,canteen in nepal, student order, canteen order, online canteen, khaja, momo, chaumin " />
        <meta property="og:title" content="Collegekhajghar:IIC Nepal|first online cateen, food order"/>
        <title>{% block title %}{% endblock %}</title>
        <link rel="shortcut icon" type="image/png" href="media/products/foodIcon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Boostrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
       {% load static %}
        <link rel="stylesheet" href="{% static 'css/navigation.css'%}">
        {% block extraheading %}
        {% endblock %}
    </head>
    <body id="body-pd">
        <header class="header" id="header">
            <div class="header__toggle">
                <i class='bx bx-menu' id="header-toggle"></i>
            </div>
            <form class="form-inline my-2 my-lg-0 outafter" action="{% url 'collegekhajaghar:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if request.user.customer %}
            <div class="header__img">
                <a href="{% url 'collegekhajaghar:customerprofile' %}">
                    <img src="{% static 'displayPicture/profile.jpg '%}" alt="picture">
                </a>
            </div>
            {% endif %}
        </header>
            <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div>
                    <a href="{% url 'collegekhajaghar:home' %}" class="nav__logo">
                        <img src="{% static 'foodlogo/foodIcon.png'%}" width="20px" height="30px" alt="logo">
                        <span class="nav__logo-name">IIC Khajaghar</span>
                    </a>

                    <div class="nav__list">
                        <a href="{% url 'collegekhajaghar:home' %}" class="nav__link">
                            <i class='bx bx-grid-alt nav__icon' ></i>
                            <span class="nav__name">Dishes</span>
                        </a>
                        <a href="{% url 'collegekhajaghar:allproducts' %}" class="nav__link">
                            <i class='bx bxs-food-menu nav__icon' ></i>
                            <span class="nav__name">Menu</span>
                        </a>
                        <a href="{% url 'collegekhajaghar:mycart' %}" class="nav__link">
                            <i class='bx bxs-cart-add nav__icon' ></i>
                            <span class="nav__name">Cart</span>
                        </a>
                        {% if request.user.customer %}
                        <a href="{% url 'collegekhajaghar:csorder' %}" class="nav__link">
                            <i class='bx bx-sort-up nav__icon' ></i>
                            <span class="nav__name">Order</span>
                        </a>

                        <a href="{% url 'collegekhajaghar:customerprofile' %}" class="nav__link ">
                            <i class='bx bx-user nav__icon' ></i>
                            <span class="nav__name">Profile</span>
                        </a>
                        {% else %}
                        <a href="{% url 'collegekhajaghar:customerlogin' %}" class="nav__link">
                            <i class='bx bx-log-in nav__icon' ></i>
                            <span class="nav__name">Login</span>
                        </a>
                        <a href="{% url 'collegekhajaghar:customerregistration' %}" class="nav__link">
                            <i class='bx bxs-user-plus nav__icon'></i>
                            <span class="nav__name">Register</span>
                        </a>
                        {% endif %}
                        {% if request.user.customer %}
                        <a href="{% url 'collegekhajaghar:about' %}" class="nav__link">
                            <i class='bx bx-bar-chart-alt-2 nav__icon' ></i>
                            <span class="nav__name">About Us</span>
                        </a>
                        {% endif %}
                        </a>
                    </div>
                        {% if request.user.customer %}
                        <a href="{% url 'collegekhajaghar:customerlogout' %}" class="nav__link">
                            <i class='bx bx-log-out nav__icon' ></i>
                            <span class="nav__name">Log Out</span>
                        </a>
                        {% endif %}
                </div>
            </nav>
      </div>
        {% block content %}
        {% endblock %}
        <!--===== MAIN JS =====-->
        <script src="{% static 'js/base.js'%}"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block jscontent %}
        {% endblock %}
    </body>
</html>


ckgproject/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Checkout {% endblock %}
{% block extraheading %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row  mt-10">
        <div class="col-md-6  border">
            <h3>Items in the cart</h3>
            <a href="{% url 'collegekhajaghar:mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6 border rounded ">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info ">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/contactus.html
{% extends 'base.html' %}

{% block title %}Contact us{% endblock %}

{% block content %}
    <h1>To Contact us, Call the following numbers</h1>
    <p>989898989898</p>
    <p>989898989898</p>
{% endblock %}

ckgproject/templates/customerdashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}
{% block extraheading %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
<div class="container">
    <h5 class=""><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
    {% for l in data %}
        <div>
            <h1>Here is list of customer: {{ l }}</h1>
        </div>
    {% endfor %}
</div>
{% endblock %}

ckgproject/templates/customerlogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Customer Login{% endblock %}
{% block extraheading %}
    <link rel="stylesheet" href="{% static 'css/customerlogin.css '%}">
{% endblock %}
{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <br>
            <br>
            <h3 style="text-align: center">Collegekhajaghar Login </h3>
            <div class=" border border-white p-3 rounded formclr m-2">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary">Login as a Customer</button>
                    {% if error %}
                    <li style="color: red;">{{error}}</li>
                    {% endif %}
                </form>
            </div>
            <p>Forgot Password?<a href="{% url 'collegekhajaghar:passwordforgot' %}">Reset now.</a> <span style="padding-left:124px;">New Here: <a href="{% url 'collegekhajaghar:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register</a></span></p>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/customerregistration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Customer Registration{% endblock %}
{% block extraheading %}
    <link rel="stylesheet" href="{% static 'css/customerregistration.css '%}">
{% endblock %}
{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container bcr">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class="m-2 pr-8">CKG Registration Form</h3>
            <div class=" border border-white p-3 rounded formclr m-2">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary">Register as a Customer</button>
                </form>
                <p> Already have an account? <a href="{% url 'collegekhajaghar:customerlogin' %}">Login here</a></p>


            </div>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/forgetpassword.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Forgot password{% endblock %}
{% block extraheading %}
    <link rel="stylesheet" href="{% static 'css/forgetpassword.css '%}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <br>
            <br>
            <br>
            {% if request.GET.m == "s" %}
            <h3>Password reset link is sent to your email address. Please check your email immediately. </h3>
            {% else %}
            <h3 class="aligncenter">Enter your recover Email Address</h3>
            {% if request.GET.m == "e" %}
            <h4 class="text-danger">Invalid Email, Enter valid email again</h4>
            {% endif %}
            <div class="border border-white p-3 rounded formclr ml-10">
                <form action="" method="POST">
                    {% csrf_token %}
                    <h3 class="aligncenter">Forget Password?</h3>
                    {{form.as_p}}
                    <button> Get Reset Link</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}


ckgproject/templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} (Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            {% if product.normal_price == None %}
                <p class="mt-3">Price: Rs.{{product.offer_price}}</p> <P style="display:none">{{product.normal_price}}</P>
            {% else %}
                <p class="mt-3">Price: Rs.{{product.offer_price}} <strike>Rs.{{product.normal_price}}</strike></p>
            {% endif %}
            <a href="{% url 'collegekhajaghar:addtocart' product.id %}" class="btn btn-info">Add To Cart</a>
            <hr>
            <p class="text-info">Carbohydrate Amount: {{product.carbohydrate}} calories</p>
            <p class="text-info">Protein Amount: {{product.protein}} calories</p>
            <p class="text-info">Fat Amount: {{product.fats}} calories</p>
            <p class="text-info">Other energy: {{product.other_energy}} calories</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>
    <hr>
    <div class="container p-0 m-0">
        <h3 class="text-center">Total Reviews: {{ product.review_set.count }}</h3>
        <hr>
        <div class="row">
            {% if request.user.customer %}
            <div class="col-5 p-0 m-0">
                <h4>Previous Review</h4>
                {% for review in product.review_set.all %}
                <div >
                    <i class='bx bxs-user nav__icon'></i>
                    <div class="media-body">
                        <div class="small">
                            <b>{{review.user.username}}</b>
                            <time class="ml-4 opacity-70 ">{{review.date_time}}</time>
                        </div>
                        <p>{{review.comment}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="col-12 p-0 m-0">
                <h3 class="text-center" ><a href="{% url 'collegekhajaghar:customerlogin' %}">Login to see dish's review</a></h3>
            </div>

            {% endif %}
            {% if request.user.customer %}
            <div class="col-md-7">
                <form action="{% url 'collegekhajaghar:productdetail' slug=product.slug %}" method="POST">                   {% csrf_token %}
                    <div class="form-group">
                        <p>{{form.comment}}</p>
                    </div>
                    <button class="btn btn-primary btn-block">Add Review</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
<!--    <div class="section">-->
<!--        <div class="container">-->
<!--            <h3 class="text-center">Total Reviews: {{ reviews_count }}</h3>-->
<!--            <div class="row">-->
<!--                <div class="col-lg-8">-->
<!--                    <div class="media-list">-->
<!--                        <form action="{% url 'collegekhajaghar:productdetail' slug=product.slug %}" method="POST">-->
<!--                            {% csrf_token %}-->
<!--                            <div class="form-group">-->
<!--                                <p>{{form.comment}}</p>-->
<!--                            </div>-->
<!--                            <button class="btn btn-primary btn-block">Add Review</button>-->
<!--                        </form>-->
<!--                        <br>-->
<!--                        <hr>-->
<!--                        <h4>Previous Review</h4>-->
<!--                        {% for review in reviews%}-->
<!--                        <div>-->
<!--                            <i class='bx bxs-user nav__icon'></i>-->
<!--                            <div class="media-body">-->
<!--                                <div class="small">-->
<!--                                    <b>{{review.user.username}}</b>-->
<!--                                    <time class="ml-4 opacity-70 ">{{review.date_time}}</time>-->
<!--                                </div>-->
<!--                                <p>{{review.comment}}</p>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        {% endfor %}-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-lg-8 mx-auto">-->

<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>
{% endblock %}

ckgproject/templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% if results < 1 %}
                    <h1>No Result is found</h1>
            {% else %}
                {% for result in results %}
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{result.image.url}}" class="img-fluid" alt="">
                    </div>
                    <div class="col-md-9">
                        <h4><a href="{% url 'collegekhajaghar:productdetail' result.slug %}">{{result.title}}</a></h4>
                        <p>{{result.description|truncatewords:10}}</p>
                        <a href="{% url 'collegekhajaghar:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

ckgproject/templates/testing.html
{% extends 'base.html' %}

{% block title %}All reviews{% endblock %}

{% block content %}
    <p class="container">
        <p class="row">
            <p class="col-md-2">
                {% for i in allreviews %}
                    <p><b>Review of product: {{i.product}}</b></p>
                    <p><b>Reviewed by: {{i.user.username}}</b></p>
                    <p>{{i.rating}}</p>
                    <p>{{i.comment}}</p>
                {% endfor %}

            </p>

        </p>
    </p>

{% endblock %}