ckgproject/ckgproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path("", include("collegekhajagharapp.urls")),
    path("jsi18n/", JavaScriptCatalog.as_view, name="js-catalog"),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



ckgproject/collegekhajagharapp/urls.py
from django.urls import path, re_path
from .views import *
from . import views
app_name = "collegekhajaghar"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("Dashboard/", views.DashboardView, name="csdashboard"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("order/", CustomerOrderView.as_view(), name="csorder"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
    # path("products/<slug:slug>/", views.add_review, name="addreview"),

    path("add-to-cart-<int:dish_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("staff-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("staff-home/", AdminHomeView.as_view(), name="adminhome"),
    path("staff-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("staff-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("staff-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("staff-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("staff-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
]

ckgproject/collegekhajagharapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="CKG Staff")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    offer_price = models.PositiveIntegerField()
    normal_price = models.PositiveIntegerField(null=True, blank=True)
    carbohydrate = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    fats = models.DecimalField(max_digits=5, decimal_places=2)
    other_energy = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    view_count = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart Number({1}) of customer {0} ".format(self.customer, str(self.id))


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Pending", "Order Pending"),
    ("Order Received", "Order Received"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash", "Cash"),
    ("Khalti", "Khalti"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=30)
    preffered_date_time = models.DateTimeField(auto_now_add=False, auto_now=False)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    order_created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order Number({1}) of {0} ".format(self.ordered_by, str(self.id))

    @property
    def time_left_minutes(self):
        timenow = self.preffered_date_time
        now = datetime.now()
        result = timenow - now
        if result >= 0:
            return result.minutes
        else:
            return "Time out"

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(max_length=100)

    def __str__(self):
        return self.user.username

ckgproject/templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
     <link rel="shortcut icon" type="image/png" href="../../media/products/foodIcon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'cssadmin/adminindex.css' %}" />
    {% block headadmin %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body id="body">
    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a href="{% url 'collegekhajaghar:home' %}" target="_blank">Customers sites</a>
          <a class="active_link" href="#">Staff_sites</a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->
            {% block content %}

            {% endblock %}
        </div>

      </main>

      <div id="sidebar">
        <div class="sidebar__title">
          <div class="sidebar__img">
            <h1>Collegekhajaghar</h1>
          </div>
          <i
            onclick="closeSidebar()"
            class="fa fa-times"
            id="sidebarIcon"
            aria-hidden="true"
          ></i>
        </div>

        <div class="sidebar__menu">
          <div class="sidebar__link">
            <i class="fa fa-home"></i>
            <a href="{% url 'collegekhajaghar:adminhome'%}">Dashboard</a>
          </div>
          <h2>links</h2>
          <div class="sidebar__link ">
            <i class="fa fa-user-secret" aria-hidden="true"></i>
            <a href="{% url 'collegekhajaghar:adminorderlist'%}">All Orders</a>
          </div>
          <div class="sidebar__link active_menu_link">
            <i class="fa fa-building-o"></i>
            <a href="{% url 'collegekhajaghar:adminproductlist' %}">All Dishes</a>
          </div>

          <br>
          <br>
          <div class="sidebar__logout">
            <i class="fa fa-power-off"></i>
            <a href="{% url 'collegekhajaghar:customerlogout' %}">Log out</a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="{% static 'jsadmin/adminindex.js' %}"></script>
  </body>
</html>
















ckgproject/templates/adminpages/admindashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'cssadmin/adminindex.css' %}" />
    <title>Hello world</title>
  </head>
  <body id="body">
    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a href="#">Customers sites</a>
          <a class="active_link" href="#">Staff_sites</a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="assets/hello.svg" alt="" />
            <div class="main__greeting">
              <h1>Hello</h1>
              <p>Welcome to your CKG Staff dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Subscribers</p>
                <span class="font-bold text-title">578</span>
              </div>
            </div>

            <div class="card">
              <i class="fa fa-calendar fa-2x text-red" aria-hidden="true"></i>
              <div class="card_inner">
                <p class="text-primary-p">Times of Watching</p>
                <span class="font-bold text-title">2467</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-video-camera fa-2x text-yellow"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Videos</p>
                <span class="font-bold text-title">340</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-thumbs-up fa-2x text-green"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Likes</p>
                <span class="font-bold text-title">645</span>
              </div>
            </div>
          </div>
          <!-- MAIN CARDS ENDS HERE -->

          <!-- CHARTS STARTS HERE -->
          <div class="charts">
            <div class="charts__left">
              <div class="charts__left__title">
                <div>
                  <h1>Daily Reports</h1>
                  <p>Cupertino, California, USA</p>
                </div>
                <i class="fa fa-usd" aria-hidden="true"></i>
              </div>
              <div id="apex1"></div>
            </div>

            <div class="charts__right">
              <div class="charts__right__title">
                <div>
                  <h1>Stats Reports</h1>
                  <p>Cupertino, California, USA</p>
                </div>
                <i class="fa fa-usd" aria-hidden="true"></i>
              </div>

              <div class="charts__right__cards">
                <div class="card1">
                  <h1>Income</h1>
                  <p>$75,300</p>
                </div>

                <div class="card2">
                  <h1>Sales</h1>
                  <p>$124,200</p>
                </div>

                <div class="card3">
                  <h1>Users</h1>
                  <p>3900</p>
                </div>

                <div class="card4">
                  <h1>Orders</h1>
                  <p>1881</p>
                </div>
              </div>
            </div>
          </div>
          <!-- CHARTS ENDS HERE -->
        </div>
      </main>

      <div id="sidebar">
        <div class="sidebar__title">
          <div class="sidebar__img">
            <img src="assets/logo.png" alt="logo" />
            <h1>Collegekhajaghar</h1>
          </div>
          <i
            onclick="closeSidebar()"
            class="fa fa-times"
            id="sidebarIcon"
            aria-hidden="true"
          ></i>
        </div>

        <div class="sidebar__menu">
          <div class="sidebar__link active_menu_link">
            <i class="fa fa-home"></i>
            <a href="{% url 'collegekhajaghar:adminhome'%}">Dashboard</a>
          </div>
          <h2>MNG</h2>
          <div class="sidebar__link">
            <i class="fa fa-user-secret" aria-hidden="true"></i>
            <a href="{% url 'collegekhajaghar:adminorderlist'%}">All Orders</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-building-o"></i>
            <a href="{% url 'collegekhajaghar:adminproductlist' %}">All Product</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-wrench"></i>
            <a href="{% url 'collegekhajaghar:adminhome'%}">Employee Management</a>
          </div>
          <div class="sidebar__logout">
            <i class="fa fa-power-off"></i>
            <a href="{% url 'collegekhajaghar:customerlogout' %}">Log out</a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="{% static 'jsadmin/adminindex.js' %}"></script>
  </body>
</html>

ckgproject/templates/adminpages/adminhome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'cssadmin/adminindex.css' %}" />
    <title>Hello world</title>
  </head>
  <body id="body">
    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a href="{% url 'collegekhajaghar:home' %}" target="_blank">Customers sites</a>
          <a class="active_link" href="#">Staff_sites</a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="assets/hello.svg" alt="" />
            <div class="main__greeting">
              <h1>Hello Staff, Ramesh</h1>
              <p>Welcome to your CKG Staff dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Registred Customer</p>
                <span class="font-bold text-title"></span>
              </div>
            </div>

            <div class="card">
              <i class="fas fa-hamburger fa-2x text-red" aria-hidden="true"></i>
              <div class="card_inner">
                <p class="text-primary-p">Total Product</p>
                <span class="font-bold text-title">4</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-video-camera fa-2x text-yellow"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Total dish Views</p>
                <span class="font-bold text-title">40</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-comments fa-2x text-green"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of reviews</p>
                <span class="font-bold text-title">4</span>
              </div>
            </div>
          </div>
          <!-- MAIN CARDS ENDS HERE -->

          <!-- CHARTS STARTS HERE -->
          <div class="charts">
            <div class="charts__left">
              <div class="charts__left__title">
                <div>
                  <h1>Monthly Reports</h1>
                  <p>IIC khajaghar</p>
                </div>
                <i class="fa fa-usd" aria-hidden="true"></i>
              </div>
              <div id="apex1"></div>
            </div>

            <div class="charts__right">
              <div class="charts__right__title">
                <div>
                  <h1>IICKhajaghar Stastics</h1>
                </div>
                <i class="fa fa-npr" aria-hidden="true"></i>
              </div>

              <div class="charts__right__cards">
                <div class="card1">
                  <h1>Total Sales</h1>
                  <p>Rs 200</p>
                </div>

                <div class="card2">
                  <h1>Total Order</h1>
                  <p>1(Received)</p>
                </div>
              </div>
            </div>
          </div>
          <!-- CHARTS ENDS HERE -->
        </div>
      </main>

      <div id="sidebar">
        <div class="sidebar__title">
          <div class="sidebar__img">
            <h1>Collegekhajaghar</h1>
          </div>
          <i
            onclick="closeSidebar()"
            class="fa fa-times"
            id="sidebarIcon"
            aria-hidden="true"
          ></i>
        </div>

        <div class="sidebar__menu">
          <div class="sidebar__link active_menu_link">
            <i class="fa fa-home"></i>
            <a href="{% url 'collegekhajaghar:adminhome'%}">Dashboard</a>
          </div>
          <h2>links</h2>
          <div class="sidebar__link">
            <i class="fa fa-user-secret" aria-hidden="true"></i>
            <a href="{% url 'collegekhajaghar:adminorderlist'%}">All Orders</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-building-o"></i>
            <a href="{% url 'collegekhajaghar:adminproductlist' %}">All Dishes</a>
          </div>
          <div class="sidebar__logout">
            <i class="fa fa-power-off"></i>
            <a href="{% url 'collegekhajaghar:customerlogout' %}">Log out</a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="{% static 'jsadmin/adminindex.js' %}"></script>
  </body>
</html>















ckgproject/templates/adminpages/adminlogin.html
{% extends 'base.html' %}

{% block title %}Staff Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
    .btnclr{
        color: white;
        background: #232923;
    }
</style>
<div class="container">
    <div class="row mt-3">
        <div class="col-md-6 mx-auto">
            <h3 class="text-center mt-3">Staff Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btnclr btn-lg btn-block">Login as Staff</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}

{% block title %}Order Detail{% endblock  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <h3>Order Detail</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span  class="font-weight-bold">Order time: </span>13 minutes ago</p>
            <p><span class="font-weight-bold">Preferred Time: </span> {{ord_obj.preffered_date_time}}{{ord_obj.created_at|timesince}}</p>
            <p><span class="font-weight-bold">User Information: </span>{{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Payment Details: </span>{{ord_obj.payment_method}} ({% if ord_obj.payment_completed %}Payment Completed{% else %}Not Paid{% endif %})</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank"
                                href="{% url 'collegekhajaghar:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a>
                        </td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
            <form action="{% url 'collegekhajaghar:adminorderstatuschange' ord_obj.id %}" method="POST">
                {% csrf_token %}
                <select name="status">
                    {% for i, j in allstatus %}
                    <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-info">Change</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}
{% block title %}Order list-Staff{% endblock %}
{% block headadmin %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
{% endblock %}

{% block content %}
    <div class="container-fluid">
       <div class="row">
           <div class="col-md-12">
               <h3>Pending Orders</h3>
               <table class="table">
                   <thead>
                       <tr>
                           <th>SN</th>
                           <th>Order ID </th>
                           <th>User</th>
                           <th>Preferred datetime</th>
                           <th>Amount</th>
                           <th>Status</th>
                       </tr>
                   </thead>
                   <tbody>
                       {% for order in pendingorders %}
                       <tr>
                           <td>{{forloop.counter}}</td>
                           <td><a href="{% url 'collegekhajaghar:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                           <td>{{order.ordered_by}}</td>
                           <td>{{order.preffered_date_time}}</td>
                           <td>{{order.total}}</td>
                           {% if order.order_status == "Order Canceled" %}
                               <td class="text-light bg-danger">{{order.order_status}}</td>
                           {% elif order.order_status == "Order Pending" %}
                               <td class="text-light bg-warning">{{order.order_status}}</td>
                           {% else %}
                               <td class="text-white bg-success">{{order.order_status}}</td>
                           {% endif %}
                       </tr>
                       {% endfor %}
                   </tbody>
               </table>
           </div>
       </div>
    </div>
{% endblock %}



ckgproject/templates/adminpages/adminproductcreate.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Add New Product{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <h3>Add New Dish</h3>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Add Dish</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ckgproject/templates/adminpages/adminproductlist.html
{% extends 'adminpages/adminbase.html' %}
{% block title %}All Products{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h3>All Product list</h3><hr>
            <a href="{% url 'collegekhajaghar:adminproductcreate' %}">Add New Dish</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product Title</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Views</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in allproducts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.title}}</td>
                        <td><img src="{{p.image.url}}" style="height: 60px;" alt=""></td>
                        <td>{{p.offer_price}}</td>
                        <td>{{p.view_count}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

